[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ha_mqtt_sdk"
version = "0.1.0"
description = "Home Assistant MQTT SDK for discovery, topics, and device management"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"

authors = [
	{ name = "Dick Kouwenhoven", email = "dick.kouwenhoven@planet.nl" }
]

keywords = [
	"homeassistant",
	"mqtt",
	"iot",
	"sdk",
	"automation",
	"python",
	"smarthome",
]

classifiers = [
	"Development Status :: 3 - Alpha",
	"Intended Audience :: Developers",
	"Topic :: Home Automation",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3.14",
]

dependencies = [
	"paho-mqtt>=2.1.0",
	"aiomqtt>=2.5.1",	
]

[project.optional-dependencies]
dev = [
	"pytest",
	"pytest-cov"
]

[project.urls]
Homepage = "https://github.com/dickkouwenhoven/HA-MQTT-SDK"
Repository = "https://github.com/dickkouwenhoven/HA-MQTT-SDK"
Issues = "https://github.com/dickkouwenhoven/HA-MQTT-SDK/issues"

# -------------------------
# Packaging config
# -------------------------

[tool.setuptools.packages.find]
where = ["."]
include = ["ha_mqtt_sdk*"]

[tool.setuptools]
include-package-data = true

# -------------------------
# Optional dev tools
# -------------------------

[tool.pytest.ini_options]
pythonpath=["."]
testpaths = ["tests"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["ha_mqtt_sdk"]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = false

